### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by RuyaSavascisi**

### CODE REVIEW

**Comment by RuyaSavascisi** [comment]
where is the sign area

**Comment by 4c65736975** [comment]
> where is the sign area

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by RuyaSavascisi** [comment]
why i need to sign the commit, i'm just sending translation

**Comment by 4c65736975** [comment]
It's a branch protection rule, all commits have to be signed, even if I wanted to I couldn't merge this pull request

**Pull request closed without merging**
